### ISSUE TITLE
NodeEngine unable to register to netmanager

### ISSUE THREAD

**Issue by melkodary** [oakestra/oakestra#336]
## Short
When running the NodeEngine with the Netmanager, the NodeEngine exits because it's unable to register to the NetManager.
## Proposal:

**NodeEngine error:**
```
ERROR-2024/06/02 17:13:24 NodeEngine.go:47: Unable to register to NetManager: Post "http://localhost:6000/register": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

**NetManager logs:**
```
2024/06/02 17:13:14 Local Interface in use:  enp0s1  with addr  192.168.67.2
INFO-2024/06/02 17:13:14 ProxySetup.go:89: Created ProxyTun device: goProxyTun
INFO-2024/06/02 17:13:14 ProxySetup.go:90: Local Ip detected: 192.168.67.2
INFO-2024/06/02 17:13:14 ProxySetup.go:106: Starting proxy listening mode
INFO-2024/06/02 17:13:14 EnvironmentManager.go:141: Asking the cluster for a new subnetwork
INFO-2024/06/02 17:13:14 ProxyTunnel.go:265: GoProxyTunnel outgoing listening started
INFO-2024/06/02 17:13:14 ProxyTunnel.go:295: GoProxyTunnel ingoing listening started
ERROR-2024/06/02 17:13:14 v6Packet.go:96: Could not determine TransportLayer of IPv6 Packet.
ERROR-2024/06/02 17:13:18 v6Packet.go:96: Could not determine TransportLayer of IPv6 Packet.
2024/06/02 17:13:24 TIMEOUT - Table query without response, quitting goroutine
2024/06/02 17:13:24 Invalid subnetwork received. Can't proceed.
```

**cluster service manager is reporting the following:**
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1164, in _loop
    rc = self.loop_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 1556, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 2439, in _packet_read
    rc = self._packet_handle()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3033, in _packet_handle
    return self._handle_publish()
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3330, in _handle_publish
    self._handle_on_message(message)
  File "/usr/local/lib/python3.8/site-packages/paho/mqtt/client.py", line 3570, in _handle_on_message
    on_message(self, self._userdata, message)
  File "/interfaces/mqtt_client.py", line 51, in handle_mqtt_message
    _subnet_handler(client_id, payload)
  File "/interfaces/mqtt_client.py", line 138, in _subnet_handler
    mongo_find_node_by_id_and_update_subnetwork(client_id, addr[0], addr[1])
TypeError: 'NoneType' object is not subscriptable
```

**To reproduce:**
- running the 1-DOC.yaml: `docker compose -f 1-DOC.yaml -f override-alpha-versions-v301.yaml up -d`

**Comment by smnzlnsk** [comment]
@melkodary Can you tell me what branches you used?

**Comment by melkodary** [comment]
Develop

**Comment by smnzlnsk** [comment]
Where did you find the override file? It's not located in run-a-cluster/ on the develop branch

**Comment by melkodary** [comment]
doesn't crash on a different enivronment/machine, so will close this.
